DROP TABLE IF EXISTS painel_gestao.stg_perfil_clientes_raw;

CREATE TABLE painel_gestao.stg_perfil_clientes_raw (
    id_carga BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,

    JUNCAO_AGENCIA VARCHAR(255),
    CONTA VARCHAR(255),
    CNPJ_BASICO VARCHAR(255),
    CNPJ_COMPLETO VARCHAR(255),
    RAZAO_SOCIAL VARCHAR(255),
    NOME_GERENTE VARCHAR(255),
    FUNCAO VARCHAR(255),
    COD_CLIE VARCHAR(255),
    SUBSEGMENTO VARCHAR(255),
    SUBSEGMENTO_AJUSTADO VARCHAR(255),
    MAIOR_SUBSEGMENTO_AJUSTADO VARCHAR(255),
    DT_FUNDACAO VARCHAR(255),
    DT_ABERT_CTA VARCHAR(255),
    DULT_MOVTO_CTA VARCHAR(255),
    STATUS_CONTA VARCHAR(255),
    MUNICIPIO VARCHAR(255),
    UF VARCHAR(255),
    SITUACAO_RECEITA VARCHAR(255),
    SECAO_CNAE VARCHAR(255),
    DIVISAO_CNAE VARCHAR(255),
    GRUPO_CNAE VARCHAR(255),
    CLASS_CNAE VARCHAR(255),
    ATIVIDADE_CNAE VARCHAR(255),
    COD_CNAE VARCHAR(255),
    COD_NATUREZA VARCHAR(255),
    CEP VARCHAR(255),
    ENDERECO VARCHAR(255),
    RATING VARCHAR(255),
    GRAU_DE_RESTRICAO VARCHAR(255),
    PERFIL VARCHAR(255),
    PERFIL_RISCO VARCHAR(255),
    PORTE_EMPRESA VARCHAR(255),
    ANOS_FUNDACAO VARCHAR(255),
    ANOS_RELACIONAMENTO VARCHAR(255),
    ROB VARCHAR(255),
    FATURAMENTO_VUC VARCHAR(255),
    `Indice Perfil Risco` VARCHAR(255),
    AgConta VARCHAR(255),
    ANOMES VARCHAR(255),

    TOTAL_PRODUTOS VARCHAR(255),
    POSSUI_OPEN VARCHAR(255),
    POSSUI_ALELO VARCHAR(255),
    POSSUI_CIELO VARCHAR(255),
    POSSUI_CTA_GARANTIDA VARCHAR(255),
    POSSUI_CHEQUE VARCHAR(255),
    POSSUI_CDC VARCHAR(255),
    POSSUI_DESCONTO VARCHAR(255),
    POSSUI_CAGIRO VARCHAR(255),
    POSSUI_CREDITO VARCHAR(255),
    POSSUI_DEBITO_AUTOMATICO VARCHAR(255),
    POSSUI_CONSORCIO_PESADOS VARCHAR(255),
    POSSUI_CONSORCIO_IMOVEL VARCHAR(255),
    POSSUI_CONSORCIO_AUTO VARCHAR(255),
    POSSUI_PREVIDENCIA VARCHAR(255),
    POSSUI_SEGURO_SAUDE VARCHAR(255),
    POSSUI_SEGURO_AUTO VARCHAR(255),
    POSSUI_SEGURO_DENTAL VARCHAR(255),
    POSSUI_SEGURO_VIDA VARCHAR(255),
    POSSUI_POUPANCA VARCHAR(255),
    POSSUI_LCA VARCHAR(255),
    POSSUI_LCI VARCHAR(255),
    POSSUI_CORRETORA VARCHAR(255),
    POSSUI_FUNDOS VARCHAR(255),
    POSSUI_CDB VARCHAR(255),
    POSSUI_CARTAO VARCHAR(255),
    POSSUI_FOLHA VARCHAR(255),
    POSSUI_INVEST_FACIL VARCHAR(255),
    POSSUI_INVESTIMENTO VARCHAR(255),
    POSSUI_PIX VARCHAR(255),
    POSSUI_PIX_CHAVE VARCHAR(255),
    POSSUI_M_TOKEN VARCHAR(255),
    POSSUI_CAMBIO_PRONTO VARCHAR(255),
    POSSUI_VELOE VARCHAR(255),
    POSSUI_RECEBIDOS VARCHAR(255),
    POSSUI_ROTATIVOS_NOVOS VARCHAR(255),
    POSSUI_CONSORCIO VARCHAR(255),
    POSSUI_SEGUROS VARCHAR(255),
    POSSUI_CIELO_LEGADO VARCHAR(255),
    POSSUI_CIELO_NOVO VARCHAR(255),
    POSSUI_BOLETO VARCHAR(255),

    VALOR_RECEBIDO VARCHAR(255),
    VALOR_ENVIADO VARCHAR(255),
    MEDALHA_CASH VARCHAR(255),
    MEDALHA_RISCO VARCHAR(255),
    MEDALHA_PRODUTO VARCHAR(255),
    MEDALHAS VARCHAR(255),
    NIVEL_CONECTA VARCHAR(255),
    NIVEL_POR_ROB VARCHAR(255),
    PCT_CASH VARCHAR(255),
    PCT_RISCO VARCHAR(255),
    PRODUTOS_GRUPO VARCHAR(255),
    DATA_GRADUACAO VARCHAR(255),
    FATURAMENTO_BRA VARCHAR(255),
    RENC_SEM_PPC VARCHAR(255),
    SOMA_ROB VARCHAR(255),
    CAPTACAO VARCHAR(255),
    APLICACAO VARCHAR(255),
    RECEITA_SERVICOS VARCHAR(255),
    RECEITA_LIGADAS VARCHAR(255),
    RESULTADO VARCHAR(255),
    SALDO_MEDIO VARCHAR(255),
    RAR_VALOR VARCHAR(255),
    PDD_PERCENTUAL VARCHAR(255),
    DIGITAL VARCHAR(255),

    dt_carga DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id_carga)
);
SELECT @@hostname AS host, @@port AS porta, VERSION() AS versao;



SELECT
    USER() AS usuario_conexao,
    CURRENT_USER() AS usuario_autenticado,
    @@port AS porta;
SHOW WARNINGS;


CREATE USER 'etl_painel'@'localhost'
IDENTIFIED BY 'EtL@Painel2026!';

GRANT
    SELECT,
    INSERT,
    UPDATE,
    DELETE,
    CREATE,
    DROP,
    ALTER,
    INDEX
ON painel_gestao.*
TO 'etl_painel'@'localhost';

FLUSH PRIVILEGES;


SELECT user, host, plugin
FROM mysql.user
WHERE user = 'etl_painel';stg_perfil_clientes_raw